#!/bin/bash
#
# build.sh - language-agnostic backend build dispatcher.
#
# Detects the backend's programming language from marker files inside
# src/server/ and builds it into src/server/out/video-server (or
# video-server.exe on Windows). The output binary is the SAME name
# regardless of language, so CI, bin/detect.ts, and the release assets
# never need to change when the language changes.
#
# To support a new language: add a marker check in `detect_language` and a
# `case` branch below. No workflow files need to be edited for a supported
# language — the workflows only call `bash build.sh`.
#
# Env vars honoured (passed through to the language build):
#   TARGET_OS   - force target OS (e.g. "windows") instead of uname
#   CXX, CC     - C/C++ compilers (C++ backend)
#   EXTRA_CFLAGS- extra compiler flags (C++ backend)
#
set -e

ROOT="$(cd "$(dirname "$0")" && pwd)"
SRV="$ROOT/src/server"
OUT="$SRV/out"
mkdir -p "$OUT"

detect_language() {
    [ -f "$SRV/Cargo.toml" ] && { echo rust; return; }
    [ -f "$SRV/go.mod" ] && { echo go; return; }
    { [ -f "$SRV/pyproject.toml" ] || [ -f "$SRV/requirements.txt" ]; } && { echo python; return; }
    [ -f "$SRV/package.json" ] && { echo node; return; }
    [ -d "$SRV/cpp" ] && { echo cpp; return; }
    echo unknown
}

LANG="$(detect_language)"
echo "[build] Detected backend language: $LANG"

case "$LANG" in
    cpp)
        "$ROOT/build_cpp.sh"
        ;;
    rust)
        command -v cargo >/dev/null 2>&1 || {
            echo "[build] cargo not found - installing rustup..."
            curl -fsSL https://sh.rustup.rs | sh -s -- -y --profile minimal
            export PATH="$HOME/.cargo/bin:$PATH"
        }
        (cd "$SRV" && cargo build --release)
        BIN=$(find "$SRV/target/release" -maxdepth 1 -type f -perm -u+x \
              ! -name "*.d" ! -name "*.rlib" -printf '%p\n' | head -n 1)
        [ -n "$BIN" ] || { echo "[build] ERROR: no Rust binary produced" >&2; exit 1; }
        cp "$BIN" "$OUT/video-server"
        ;;
    go)
        command -v go >/dev/null 2>&1 || {
            echo "[build] go not found - please install Go first (https://go.dev)" >&2
            exit 1
        }
        (cd "$SRV" && go build -o "$OUT/video-server" .)
        ;;
    python)
        cat > "$OUT/video-server" <<'EOF'
#!/bin/sh
# Python backend launcher (generated by build.sh)
exec python3 "$(dirname "$0")/../server/main.py" "$@"
EOF
        chmod +x "$OUT/video-server"
        ;;
    node)
        cat > "$OUT/video-server" <<'EOF'
#!/bin/sh
# Node/Bun backend launcher (generated by build.sh)
exec bun run "$(dirname "$0")/../server/main.ts" "$@"
EOF
        chmod +x "$OUT/video-server"
        ;;
    *)
        echo "[build] ERROR: could not detect a backend language in $SRV" >&2
        echo "[build] Add a marker file (Cargo.toml, go.mod, pyproject.toml," >&2
        echo "[build] requirements.txt, package.json) or keep src/server/cpp/." >&2
        exit 1
        ;;
esac

echo "[build] OK: $(ls "$OUT"/video-server* 2>/dev/null || echo 'no output')"
