#!/usr/bin/env bash
#
# videohub - one-command installer for the video-player-bun app.
#
# Detects your OS and CPU, clones the source code, downloads the matching
# pre-built backend binary from the latest GitHub release, builds the
# frontend, and creates a global `videohub` command so you can just type
#   videohub
# to start the app.
#
# Usage:
#   bash install.sh            # install or update
#
# The app lives in ~/videohub (override with VIDEOHUB_DIR).
#
set -euo pipefail

REPO="fhfjjfjd/video-player-bun"
APP_NAME="videohub"
INSTALL_DIR="${VIDEOHUB_DIR:-$HOME/videohub}"
BASE_URL="https://github.com/$REPO/releases/latest/download"

info() { printf '\033[1;34m[videohub]\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m[videohub ERROR]\033[0m %s\n' "$*" >&2; exit 1; }

# --- 1. Detect OS -------------------------------------------------------------
detect_os() {
    case "$(uname -s)" in
        Darwin)
            echo darwin
            ;;
        MINGW*|MSYS*|CYGWIN*)
            echo windows
            ;;
        *)
            if [ -n "${TERMUX_VERSION:-}" ] || command -v termux-info >/dev/null 2>&1; then
                echo android
            else
                echo linux
            fi
            ;;
    esac
}

# --- 2. Detect CPU arch -------------------------------------------------------
detect_arch() {
    case "$(uname -m)" in
        x86_64|amd64|AMD64) echo x64 ;;
        aarch64|arm64|ARM64) echo arm64 ;;
        *) echo unknown ;;
    esac
}

OS="$(detect_os)"
ARCH="$(detect_arch)"
BIN_DIR="$INSTALL_DIR/bin/$OS-$ARCH"

[ "$ARCH" = "unknown" ] && die "Unsupported CPU architecture: $(uname -m)"
info "Detected platform: $OS-$ARCH"

# --- 3. Prerequisites ---------------------------------------------------------
for tool in git curl; do
    command -v "$tool" >/dev/null 2>&1 || die "Missing required tool: $tool"
done

if ! command -v bun >/dev/null 2>&1; then
    info "Bun not found - installing it with the official installer..."
    curl -fsSL https://bun.sh/install | bash
    export PATH="$HOME/.bun/bin:$PATH"
    command -v bun >/dev/null 2>&1 || die "Bun install failed. Install it manually from https://bun.sh"
fi

# --- 4. Source code -----------------------------------------------------------
if [ -d "$INSTALL_DIR/.git" ]; then
    info "Updating source in $INSTALL_DIR ..."
    git -C "$INSTALL_DIR" pull --ff-only
else
    info "Cloning source into $INSTALL_DIR ..."
    git clone --depth 1 "https://github.com/$REPO.git" "$INSTALL_DIR"
fi

cd "$INSTALL_DIR"

# --- 5. Frontend --------------------------------------------------------------
info "Installing frontend dependencies..."
bun install

info "Building frontend..."
bun run build

# --- 6. Backend binary --------------------------------------------------------
info "Downloading $OS-$ARCH backend binary..."
mkdir -p "$BIN_DIR"
ASSET="video-server-$OS-$ARCH"
TARGET="$BIN_DIR/video-server"
if [ "$OS" = "windows" ]; then
    ASSET="$ASSET.exe"
    TARGET="$TARGET.exe"
fi
curl -fsSL -o "$TARGET" "$BASE_URL/$ASSET" || die "Failed to download $ASSET from $BASE_URL"
chmod +x "$TARGET" 2>/dev/null || true

# --- 7. Create the global `videohub` command ----------------------------------
if [ "$OS" = "android" ]; then
    CMD_DIR="${PREFIX:-/data/data/com.termux/files/usr}/bin"
else
    CMD_DIR="$HOME/.local/bin"
    mkdir -p "$CMD_DIR"
fi

LAUNCHER="$CMD_DIR/$APP_NAME"
cat > "$LAUNCHER" <<EOF
#!/bin/sh
# $APP_NAME launcher (generated by install.sh)
cd "$INSTALL_DIR" || exit 1
exec bun start "\$@"
EOF
chmod +x "$LAUNCHER"

# Add CMD_DIR to PATH if it is not already there (non-Termux shells)
if [ "$OS" != "android" ]; then
    case ":$PATH:" in
        *":$CMD_DIR:"*) ;;
        *)
            profile="$HOME/.profile"
            if [ -n "${BASH_VERSION:-}" ]; then profile="$HOME/.bashrc"; fi
            if [ -n "${ZSH_VERSION:-}" ]; then profile="$HOME/.zshrc"; fi
            printf '\n# videohub\nexport PATH="%s:$PATH"\n' "$CMD_DIR" >> "$profile"
            info "Added $CMD_DIR to PATH in $profile"
            ;;
    esac
fi

# --- 8. Done ------------------------------------------------------------------
info ""
info "Install complete!"
info "  App directory : $INSTALL_DIR"
info "  Backend       : $BIN_DIR"
info "  Command       : $APP_NAME"
info ""
info "Open a NEW terminal, then run:  $APP_NAME"
