name: Build Backend Server (macOS)

on:
  workflow_dispatch:

jobs:
  build-macos-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build backend server (ARM64)
        run: CXX=clang++ CC=clang bash build.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: darwin-arm64
          path: src/server/out/
          retention-days: 30

  build-macos-x64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build backend server (x86_64)
        run: EXTRA_CFLAGS="-arch x86_64" CXX=clang++ CC=clang bash build.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: darwin-x64
          path: src/server/out/
          retention-days: 30
